baseurl = "/"
languageCode = "fr-ca"
theme = "terminal"
paginate = 5
DefaultContentLanguage = "fr"

[params]
  # dir name of your blog content (default is `content/post`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.fr]
    languageName = "Français"
    title = "Blogue de Notarock"
    subtitle = "Portfolio et blog"
    keywords = ""
    copyright = ""
    menuMore = "Plus..."
    readMore = "Lire la suite"
    readOtherPosts = "Voir les autres articles"

    [languages.fr.params.logo]
      logoText = "[notarock:~]$"
      logoHomeLink = "/"

    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "about"
        name = "A Propos"
        url = "/about"
      [[languages.fr.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/notarock"

  [languages.en]
    languageName = "English"
    title = "Notarock's blog"
    subtitle = "Portfolio and Blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "[notarock:~]$"
      logoHomeLink = "/en/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/en/about"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/notarock"
