baseurl = "/"
languageCode = "fr-ca"
title = "Notarock"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/:year/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Catégories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "Le blog de Roch D'amour"
    footer = "| [Github](https://github.com/notarock) | [Linkedin](https://www.linkedin.com/in/694958129/) | [Youtube](https://www.youtube.com/channel/UCQjr8-APqcSDEzaUp5JUYXQ) |"
    custom_css = ["css/theme-override.css"]
